/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author brand
 */
public class Questionario extends javax.swing.JFrame {

    /**
     * Creates new form Questionario
     */
    public Questionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        grupo3 = new javax.swing.ButtonGroup();
        grupo7 = new javax.swing.ButtonGroup();
        grupo8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rb2A = new javax.swing.JRadioButton();
        rb1B = new javax.swing.JRadioButton();
        rb1C = new javax.swing.JRadioButton();
        rb1D = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb1A = new javax.swing.JRadioButton();
        rb2B = new javax.swing.JRadioButton();
        rb2C = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rb3A = new javax.swing.JRadioButton();
        rb3B = new javax.swing.JRadioButton();
        rb3C = new javax.swing.JRadioButton();
        rb3D = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        rb5A = new javax.swing.JRadioButton();
        rb5B = new javax.swing.JRadioButton();
        rb5C = new javax.swing.JRadioButton();
        rb5D = new javax.swing.JRadioButton();
        rb5E = new javax.swing.JRadioButton();
        rb5F = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rb6B = new javax.swing.JRadioButton();
        rb8C = new javax.swing.JRadioButton();
        rb8D = new javax.swing.JRadioButton();
        rb7A = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rb8A = new javax.swing.JRadioButton();
        rb6D = new javax.swing.JRadioButton();
        rb6E = new javax.swing.JRadioButton();
        rb6F = new javax.swing.JRadioButton();
        txt6F = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        rb7B = new javax.swing.JRadioButton();
        rb7C = new javax.swing.JRadioButton();
        rb7D = new javax.swing.JRadioButton();
        rb8B = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rb6C = new javax.swing.JRadioButton();
        rb6A = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DADOS BÁSICOS OBRIGATÓRIOS");

        jLabel3.setText("1. Qual seu diagnóstico principal?");

        grupo2.add(rb2A);
        rb2A.setText("Menos de 1 ano");
        rb2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2AActionPerformed(evt);
            }
        });

        grupo1.add(rb1B);
        rb1B.setText("Diabetes Tipo 2");
        rb1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1BActionPerformed(evt);
            }
        });

        grupo1.add(rb1C);
        rb1C.setText("Câncer de Estômago");
        rb1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1CActionPerformed(evt);
            }
        });

        grupo1.add(rb1D);
        rb1D.setText("Ambos");
        rb1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1DActionPerformed(evt);
            }
        });

        jLabel4.setText("2. Há quanto tempo você tem esse diagnóstico?");

        grupo1.add(rb1A);
        rb1A.setText("Diabetes Tipo 1");
        rb1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1AActionPerformed(evt);
            }
        });

        grupo2.add(rb2B);
        rb2B.setText("1 a 3 anos");
        rb2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2BActionPerformed(evt);
            }
        });

        grupo2.add(rb2C);
        rb2C.setText("Mais de 3 anos");
        rb2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2CActionPerformed(evt);
            }
        });

        jLabel5.setText("3. Qual tratamento você está fazendo atualmente?");

        grupo3.add(rb3A);
        rb3A.setText("Medicamentos orais");
        rb3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3AActionPerformed(evt);
            }
        });

        grupo3.add(rb3B);
        rb3B.setText("Insulina");
        rb3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3BActionPerformed(evt);
            }
        });

        grupo3.add(rb3C);
        rb3C.setText("Quimioterapia/Radioterapia ");
        rb3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3CActionPerformed(evt);
            }
        });

        grupo3.add(rb3D);
        rb3D.setText("Combinação de tratamentos ");
        rb3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3DActionPerformed(evt);
            }
        });

        jLabel6.setText("4. Medicamentos de uso contínuo:");

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("SINTOMAS E RESTRIÇÕES");

        jLabel8.setText("5.  Principais sintomas que você apresenta:");

        rb5A.setText("Náuseas/Vômitos");
        rb5A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5AActionPerformed(evt);
            }
        });

        rb5B.setText("Perda de apetite");
        rb5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5BActionPerformed(evt);
            }
        });

        rb5C.setText("Alterações no paladar ");
        rb5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5CActionPerformed(evt);
            }
        });

        rb5D.setText("Problemas digestivos");
        rb5D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5DActionPerformed(evt);
            }
        });

        rb5E.setText("Fadiga ");
        rb5E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5EActionPerformed(evt);
            }
        });

        rb5F.setText("Nenhum sintoma significativo ");
        rb5F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5FActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb2B)
                            .addComponent(rb2A)
                            .addComponent(rb2C)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb1C)
                                    .addComponent(rb1B, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb1D, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb1A, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(213, 213, 213)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rb3A))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rb3B))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rb3C))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rb3D))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb5A)
                            .addComponent(rb5B)
                            .addComponent(rb5C)
                            .addComponent(rb5D)
                            .addComponent(rb5E)
                            .addComponent(rb5F))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb2A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb5A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5E)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb5F)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );

        rb6B.setText("Glúten");
        rb6B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6BActionPerformed(evt);
            }
        });

        grupo8.add(rb8C);
        rb8C.setText("Reduzir sintomas do tratamento ");
        rb8C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8CActionPerformed(evt);
            }
        });

        grupo8.add(rb8D);
        rb8D.setText("Melhorar qualidade de vida geral");
        rb8D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8DActionPerformed(evt);
            }
        });

        grupo7.add(rb7A);
        rb7A.setText("Sim, diariamente");
        rb7A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7AActionPerformed(evt);
            }
        });

        jLabel9.setText("7. Você faz monitoramento de glicose?");

        jLabel10.setText("8. Principal objetivo com o plano alimentar:");

        grupo8.add(rb8A);
        rb8A.setText("Controlar glicemia ");
        rb8A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8AActionPerformed(evt);
            }
        });

        rb6D.setText("Frutos do mar");
        rb6D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6DActionPerformed(evt);
            }
        });

        rb6E.setText("Nenhuma");
        rb6E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6EActionPerformed(evt);
            }
        });

        rb6F.setText("Outra:");
        rb6F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6FActionPerformed(evt);
            }
        });

        txt6F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6FActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("MONITORAMENTO E OBJETIVOS ");

        grupo7.add(rb7B);
        rb7B.setText("Sim, algumas vezes por semana");
        rb7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7BActionPerformed(evt);
            }
        });

        grupo7.add(rb7C);
        rb7C.setText("Raramente");
        rb7C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7CActionPerformed(evt);
            }
        });

        grupo7.add(rb7D);
        rb7D.setText("Não se aplica ");
        rb7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7DActionPerformed(evt);
            }
        });

        grupo8.add(rb8B);
        rb8B.setText("Ganhar/manter peso");
        rb8B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8BActionPerformed(evt);
            }
        });

        jLabel12.setText("6. Você possui alergias ou intolerâncias alimentares?");

        rb6C.setText("Nozes/Castanhas");
        rb6C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6CActionPerformed(evt);
            }
        });

        rb6A.setText(" Lactose ");
        rb6A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rb6F)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt6F, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb6E)
                    .addComponent(rb6D)
                    .addComponent(rb6C))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb6A)
                                .addComponent(rb6B)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(rb7A))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(rb7B))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(rb7C))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(rb7D))
                        .addComponent(jLabel11)
                        .addComponent(jLabel9)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb8A)
                                    .addComponent(rb8B)
                                    .addComponent(rb8C)
                                    .addComponent(rb8D))
                                .addGap(19, 19, 19))
                            .addComponent(jLabel10)))
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(rb6C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb6D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb6E)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb6F)
                    .addComponent(txt6F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addGap(5, 5, 5)
                    .addComponent(rb6A)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb6B)
                    .addGap(154, 154, 154)
                    .addComponent(jLabel11)
                    .addGap(4, 4, 4)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb7A)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb7B)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb7C)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb7D)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(rb8A)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb8B)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb8C)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rb8D)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        btnSalvar.setBackground(new java.awt.Color(51, 204, 0));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setText("SALVAR");

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUESTIONÁRIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb6BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6BActionPerformed

    private void rb8CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb8CActionPerformed

    private void rb8DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb8DActionPerformed

    private void rb7AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb7AActionPerformed

    private void rb8AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb8AActionPerformed

    private void rb6DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6DActionPerformed

    private void rb6EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6EActionPerformed

    private void rb6FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6FActionPerformed

    private void txt6FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6FActionPerformed

    private void rb7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb7BActionPerformed

    private void rb7CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb7CActionPerformed

    private void rb7DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb7DActionPerformed

    private void rb8BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb8BActionPerformed

    private void rb6CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6CActionPerformed

    private void rb6AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6AActionPerformed

    private void rb5FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5FActionPerformed

    private void rb5EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5EActionPerformed

    private void rb5DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5DActionPerformed

    private void rb5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5CActionPerformed

    private void rb5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5BActionPerformed

    private void rb5AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5AActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void rb3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3DActionPerformed

    private void rb3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3CActionPerformed

    private void rb3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3BActionPerformed

    private void rb3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3AActionPerformed

    private void rb2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2CActionPerformed

    private void rb2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2BActionPerformed

    private void rb1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1AActionPerformed

    private void rb1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1DActionPerformed

    private void rb1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1CActionPerformed

    private void rb1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1BActionPerformed

    private void rb2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2AActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.ButtonGroup grupo3;
    private javax.swing.ButtonGroup grupo7;
    private javax.swing.ButtonGroup grupo8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rb1A;
    private javax.swing.JRadioButton rb1B;
    private javax.swing.JRadioButton rb1C;
    private javax.swing.JRadioButton rb1D;
    private javax.swing.JRadioButton rb2A;
    private javax.swing.JRadioButton rb2B;
    private javax.swing.JRadioButton rb2C;
    private javax.swing.JRadioButton rb3A;
    private javax.swing.JRadioButton rb3B;
    private javax.swing.JRadioButton rb3C;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JRadioButton rb5A;
    private javax.swing.JRadioButton rb5B;
    private javax.swing.JRadioButton rb5C;
    private javax.swing.JRadioButton rb5D;
    private javax.swing.JRadioButton rb5E;
    private javax.swing.JRadioButton rb5F;
    private javax.swing.JRadioButton rb6A;
    private javax.swing.JRadioButton rb6B;
    private javax.swing.JRadioButton rb6C;
    private javax.swing.JRadioButton rb6D;
    private javax.swing.JRadioButton rb6E;
    private javax.swing.JRadioButton rb6F;
    private javax.swing.JRadioButton rb7A;
    private javax.swing.JRadioButton rb7B;
    private javax.swing.JRadioButton rb7C;
    private javax.swing.JRadioButton rb7D;
    private javax.swing.JRadioButton rb8A;
    private javax.swing.JRadioButton rb8B;
    private javax.swing.JRadioButton rb8C;
    private javax.swing.JRadioButton rb8D;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt6F;
    // End of variables declaration//GEN-END:variables
}
